### ISSUE TITLE
Can not listen to events on the latest version

### ISSUE THREAD

**Issue by nick22985** [agebrock/tunnel-ssh#106]
version: ^5.0.5

The below doesn't work you get an error
```
createTunnel(tunnelOptions, serverOptions, sshOptions, forwardOptions).then(([server, conn], error) => {
				if(error) this.$debug.extend('error')('SSH Tunnel Error', error);
				server.on('error', (err) => {
					this.$debug.extend('error')('SSH Tunnel Server', err);
				});
				conn.on('error', (err) => {
					this.$debug.extend('error')('SSH Tunnel Conn', err);
				});
			});
```

Error:
```
  mongoTunnel:error SSH Tunnel TypeError: Cannot read properties of undefined (reading 'on')
    at Socket.Readable.pipe (node:internal/streams/readable:680:8)
    at C:\Users\nick\OneDrive\Documents\Projects\Personal\discord\TrelloDiscordBot\node_modules\tunnel-ssh\index.js:66:32
    at wrapper (C:\Users\nick\OneDrive\Documents\Projects\Personal\discord\TrelloDiscordBot\node_modules\ssh2\lib\client.js:1531:5)
    at onChannelOpenFailure (C:\Users\nick\OneDrive\Documents\Projects\Personal\discord\TrelloDiscordBot\node_modules\ssh2\lib\utils.js:25:3)
    at CHANNEL_OPEN_FAILURE (C:\Users\nick\OneDrive\Documents\Projects\Personal\discord\TrelloDiscordBot\node_modules\ssh2\lib\client.js:510:11)
    at 92 (C:\Users\nick\OneDrive\Documents\Projects\Personal\discord\TrelloDiscordBot\node_modules\ssh2\lib\protocol\handlers.misc.js:810:16)
    at Protocol.onPayload (C:\Users\nick\OneDrive\Documents\Projects\Personal\discord\TrelloDiscordBot\node_modules\ssh2\lib\protocol\Protocol.js:2025:10)
    at AESGCMDecipherNative.decrypt (C:\Users\nick\OneDrive\Documents\Projects\Personal\discord\TrelloDiscordBot\node_modules\ssh2\lib\protocol\crypto.js:987:26)
    at Protocol.parsePacket [as _parse] (C:\Users\nick\OneDrive\Documents\Projects\Personal\discord\TrelloDiscordBot\node_modules\ssh2\lib\protocol\Protocol.js:1994:25)
    at Protocol.parse (C:\Users\nick\OneDrive\Documents\Projects\Personal\discord\TrelloDiscordBot\node_modules\ssh2\lib\protocol\Protocol.js:293:16) +0ms
```

**Comment by nick22985** [comment]
This actually isnt a problem with the error handle actually is the error you get back in this case just
