### ISSUE TITLE
forwardOut() fails with Connection refused error with some remote hosts

### ISSUE THREAD

**Issue by aberbegall** [agebrock/tunnel-ssh#60]
When I try to forward a local port to a remote host with this module and some hosts refuse to connect and I get the following error (DEBUG):
```js
   Error: (SSH) Channel open failure: Connection refused
       at SSH2Stream.onFailure (c:\vncclient\node_modules\ssh2\lib\client.js:1186:13)
       at Object.onceWrapper (events.js:315:30)
       at emitOne (events.js:116:13)
       at SSH2Stream.emit (events.js:211:7)
       at parsePacket (c:\vncclient\node_modules\ssh2-streams\lib\ssh.js:3708:10)
       at SSH2Stream._transform (c:\vncclient\node_modules\ssh2-streams\lib\ssh.js:669:13)
       at SSH2Stream.Transform._read (_stream_transform.js:186:10)
       at SSH2Stream._read (c:\vncclient\node_modules\ssh2-streams\lib\ssh.js:251:15)
       at SSH2Stream.Transform._write (_stream_transform.js:174:12)
       at doWrite (_stream_writable.js:387:12) +0ms
```
the 'ready' event is hit but then the forwardOut() fails and therefore the sshstream cannot be piped to the connection.

This is my implementation I provide the configuration and wait for the 'listening' event and then create a new connection to the tunnel. 
```js
   const config = {
        username: 'myuser',
        privateKey: fs.readFileSync('file.ppk'),
        passphrase: 'mypasphrase',
        host: target_host,
        dstPort: 5900,
        localPort: 0,
        localHost: 'localhost',
        readyTimeout: 99999,
        srcHost: 'localhost',
        port: 22,
    };
    sshtunnel = tunnel(config, function (error, server) {
        if (error) {console.log('error');
    });
    sshtunnel.on('listening', function () { 
        net.createConnection(sshtunnel.address().port, sshtunnel.address().address, function () {
        });
 });
```
The above code works with some hosts but others Refuse, and all host are identical. I already spent 3 full days on this issue.

This is the complete debug output from tunnel-ssh:
```js
  tunnel-ssh sshConnection:ready +224ms
Error found on ssh tunnel: { Error: (SSH) Channel open failure: Connection refused
    at SSH2Stream.onFailure (c:\vncclient\node_modules\ssh2\lib\client.js:1186:13)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at SSH2Stream.emit (events.js:211:7)
    at parsePacket (c:\vncclient\node_modules\ssh2-streams\lib\ssh.js:3708:10)
    at SSH2Stream._transform (c:\vncclient\node_modules\ssh2-streams\lib\ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (c:\vncclient\node_modules\ssh2-streams\lib\ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12) reason: 'CONNECT_FAILED', lang: '' }
  tunnel-ssh Destination port: { Error: (SSH) Channel open failure: Connection refused
    at SSH2Stream.onFailure (c:\vncclient\node_modules\ssh2\lib\client.js:1186:13)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at SSH2Stream.emit (events.js:211:7)
    at parsePacket (c:\vncclient\node_modules\ssh2-streams\lib\ssh.js:3708:10)
    at SSH2Stream._transform (c:\vncclient\node_modules\ssh2-streams\lib\ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (c:\vncclient\node_modules\ssh2-streams\lib\ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12) reason: 'CONNECT_FAILED', lang: '' } +6ms 
```

I'm running on a windows server 2012 with Node.js version 8.9.0 and the remote hosts are Linux 2.6.15.

**Comment by aberbegall** [comment]
@markelog I get the same issue with the same hosts if I use [adit](https://github.com/markelog/adit) instead of tunnel-ssh.

**Comment by aberbegall** [comment]
I keep investigating this issue... I just found that the sshd log on the Linux machine reports this:
```sh
Nov  6 12:22:57 (none) sshd[3323]: error: connect_to 127.0.0.1 port 5900: failed.
Nov  6 12:32:56 (none) sshd[603]: error: connect_to 127.0.0.1 port 5900: failed.
```
I cannot understand why it can work when using the same port forward with plink.

**Comment by aberbegall** [comment]
I keep investigating the issue, so far what I found this error in the target host log file
```
Nov  6 19:09:14 (none) sshd[2680]: error: connect_to 127.0.0.1 port 5900: failed.
```
so sshd complains that it cannot to 5900 port, and I verified that the x11vnc process was not running and therefore the port 5900 was not open. That's ok but:

In the /etc/password I have specified the following for 'myuser'
```
myuser::503:503:service:/var/home/myuser:/bin/start_x11vnc.sh
```
For each successful ssh session of 'myuser' the **start_x11vnc.sh** should run. But it does not when doing port forward with this module.

For some reason when I do the same port forward with **plink** it does work fine, the **start_x11vnc.sh** gets executed, the port 5900 is listening and the client can connect to it through the tunnel.

My question now, is why it should be different with **ssh2**? Should I try first to establish a ssh connection and then execute ForwardOut separately, to ensure the user script gets executed just before?

Any help would be very appreciated.

**Comment by aberbegall** [comment]
Hi @mscdex, perhaps you could help me here, I can also file an issue in the ssh2 if you prefer it.

**Comment by mscdex** [comment]
I'm afraid there's not much I can do if it's something server-side. Have you tried adding a statement at the top of your script that logs to a file when it's executed? That might help you narrow it down whether the script is not executing at all or just some line in the script is failing.

**Comment by aberbegall** [comment]
Thanks, that's indeed what I tried in the script start_x11vnc.sh
```
#! /bin/sh
touch /tmp/executed
```
but I only get the file created when using plink port forward.
Any ideas other ideas?

**Comment by mscdex** [comment]
No idea, maybe plink is starting an interactive shell in the background, which might cause the shell in /etc/password to be executed? For ssh in general, you can forward ports separately from interactive sessions, command executions, etc. So `tunnel-ssh` is probably doing just that, since there is usually no use in spinning up an interactive shell session for port forwarding.

**Comment by markelog** [comment]
Have you tried to create a tunnel directly with ssh i.e. without using Nodejs at all?

Regards,
Oleg

**Comment by aberbegall** [comment]
@markelog No I've never tried, I only tried with putty and plink windows clients so far

**Comment by mscdex** [comment]
@aberbegall i'd try adding `ssh.shell()` and then do `forwardOut()` inside the shell callback and see if that works.

**Comment by aberbegall** [comment]
Is it possible to force an interactive session with ssh2 before the ForwardOut()?
I have never use the ssh2 module directly.

**Comment by aberbegall** [comment]
@mscdex @markelog thanks guys for the help, I will try that ssh.shell() and see I manage to get the script executes and post some feedback here

**Comment by aberbegall** [comment]
`ssh.shell()` did the trick 👍  executing the `ssh.forwarOut()` on its callback function ensures that script execting is triggered just before.
Thank you again :)

**Comment by agebrock** [comment]
Glad you found a solution for you problem.
