### ISSUE TITLE
Error: All configured authentication methods failed

### ISSUE THREAD

**Issue by ivanbacher** [agebrock/tunnel-ssh#62]
Calling `mongoose.connect` inside of tunnel callback seems to be causing authentication errors. If i remove `mongoose.connect` no error are displayed.

I have also tried to use `monk` instead of `mongoose` but the same error pops up when `monk('user:pass@localhost:port/mydb')` is called
```

const tunnel_config = {
	username:'user',
	Password:'XXX',
	host: 'XX.XXX.XXX.XXX',
	dstHost: '127.0.0.1',
	port: 22,
	localPort: 27017,
	dstPort: 27017,
	localHost: '127.0.0.1'
};

const mongoInfo = {
    user: 'XXXX',
    pass: 'XXXXX',
    port: 27017,
    uri: '127.0.0.1',
    db: 'XXX'
}

const db_info = `${mongoInfo.user}:${mongoInfo.pass}@${mongoInfo.uri}:${mongoInfo.port}/${mongoInfo.db}`;


let connection = tunnel(tunnel_config, function (error, connection) {
    
    if(error){
        console.log("SSH connection error: " + error);
	}
    
    mongoose.connect('mongodb://user:pass@127.0.0.1:27017/XXX'); //this here seems to be causing the error
   monk('user:pass@localhost:port/mydb')  // causes same error
});
```

```
{ Error: All configured authentication methods failed
    at tryNextAuth (/Users/ivan/Workspace/Bitbucket/p-004-analysis/step_01/node_modules/ssh2/lib/client.js:376:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/Users/ivan/Workspace/Bitbucket/p-004-analysis/step_01/node_modules/ssh2/lib/client.js:587:5)
    at SSH2Stream.emit (events.js:160:13)
    at parsePacket (/Users/ivan/Workspace/Bitbucket/p-004-analysis/step_01/node_modules/ssh2-streams/lib/ssh.js:3929:10)
    at SSH2Stream._transform (/Users/ivan/Workspace/Bitbucket/p-004-analysis/step_01/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:185:10)
    at SSH2Stream._read (/Users/ivan/Workspace/Bitbucket/p-004-analysis/step_01/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:173:12)
    at doWrite (_stream_writable.js:407:12)
    at writeOrBuffer (_stream_writable.js:393:5)
    at SSH2Stream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:646:20)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10) level: 'client-authentication' }
```

**Comment by ivanbacher** [comment]
hahahaahahahahahaha figured it out.

Turns out the password property in the `tunnel_config` was spelt with a capital `P` and not a lowercase `p` 😃🤣. 

You might want to change the Config example in the `readme file`.

e.g.
Config example
   ```
 var config = {
      username:'root',
      Password:'secret', // THIS HERE SHOULD BE password NOT Password
      host:sshServer,
      port:22,
      dstHost:destinationServer,
      dstPort:27017,
      localHost:'127.0.0.1',
      localPort: 27000
    };

    var tunnel = require('tunnel-ssh');
    tunnel(config, function (error, server) {
      //....
    });
```

**Comment by waltervargas** [comment]
I added this on the index.js file for tunnel-ssh:

```js
    sshConnection.on('keyboard-interactive', function(name, instructions, instructionsLang, prompts, finish) {
        finish([config.password])
    });
```
