### ISSUE TITLE
Channel open failure: Connection refused

### ISSUE THREAD

**Issue by Saphar** [agebrock/tunnel-ssh#75]
I've not been able to get tunnel-ssh to work. I always get a connection refused error. I'm using node v10.15.1.

Here is the output:

<code>
Error: (SSH) Channel open failure: Connection refused
    at SSH2Stream.onFailure (/home/nehemiah/Local/piksie-server/node_modules/tunnel-ssh/node_modules/ssh2/lib/client.js:1186:13)
    at Object.onceWrapper (events.js:277:13)
    at SSH2Stream.emit (events.js:189:13)
    at parsePacket (/home/nehemiah/Local/piksie-server/node_modules/tunnel-ssh/node_modules/ssh2-streams/lib/ssh.js:3708:10)
    at SSH2Stream._transform (/home/nehemiah/Local/piksie-server/node_modules/tunnel-ssh/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/home/nehemiah/Local/piksie-server/node_modules/tunnel-ssh/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
Emitted 'error' event at:
    at Socket.emit (events.js:189:13)
    at /home/nehemiah/Local/piksie-server/node_modules/tunnel-ssh/index.js:19:31
    at SSH2Stream.onFailure (/home/nehemiah/Local/piksie-server/node_modules/tunnel-ssh/node_modules/ssh2/lib/client.js:1194:5)
    at Object.onceWrapper (events.js:277:13)
    [... lines matching original stack trace ...]
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
</code>

When using the exact same configuration for other SSH tasks it does work. Any help would be greatly appreciated.

**Comment by utkarsh-globant** [comment]
I am also facing the same issue, did anyone got the solution for this ?

Thanks.

**Comment by agebrock** [comment]
Unable to reproduce, please open a new issue if you have trouble with the latest version
