### ISSUE TITLE
Can't catch error: Cannot parse privateKey: Unsupported key format

### ISSUE THREAD

**Issue by safareli** [agebrock/tunnel-ssh#86]
I have `try/catch` for catching sync errors, I also check for error in callback as well as have on `"error"` handler, for catching async errors. but If invalid private key is provided to tunnel-ssh the error can't be catched. I have:

```js
const client = await new Promise((resolve, reject) => {
    try {
      tunnel(
        {
          username: ssh.username,
          host: ssh.host,
          port: ssh.port,
          dstHost: con.host,
          dstPort: con.port,
          localPort: ssh.localPort,
          privateKey: "INVALID PrivateKey",
        },
        (error: Error | null, server) => {
          if (error != null) {
            console.log("ssh tunnel creation failed", error);
            reject(error);
            return;
          }
          console.log("ssh tunnel created");
          resolve(server);
        }
      ).on("error", (error) => {
        console.error("ssh tunnel error",error);
        reject(error);
      });
    } catch (error) {
      console.error("ssh tunnel construction failed", error);
      reject(error);
    }
  });
```

and i'm getting:
```
    Cannot parse privateKey: Unsupported key format

      at Client.Object.<anonymous>.Client.connect (node_modules/ssh2/lib/client.js:225:13)
      at Server.<anonymous> (node_modules/tunnel-ssh/index.js:65:23)
```

while in logs only see `ssh tunnel created`.

versions:
- tunnel-ssh@4.1.4
- ssh2@0.5.4
- node@14.17.0

**Comment by agebrock** [comment]
Hi @safareli 

its an ssh2 issue. At this point the libs are outdated, i am going to update as soon as i can. 
Until then please check this solution: https://stackoverflow.com/questions/53400628/cannot-parse-privatekey-unsupported-key-format

**Comment by agebrock** [comment]
ssh2 updated to the latest version on version5
